# Snakefile for UCF101

import os
from os.path import join

from dotenv import load_dotenv

load_dotenv()
DATASETS_DIR = os.getenv('DATASETS_DIR')
URL = 'https://www.crcv.ucf.edu/data/UCF101/UCF101.rar'
DS_DIR = join(DATASETS_DIR, 'ucf101')
VIDEOS_DIR = join(DS_DIR, 'videos')


rule all:
  input:
    VIDEOS_DIR

rule download:
  output:
    directory(VIDEOS_DIR)
  shell:
    "python preprocess.py download"
